<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>B2B.Ordering.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/B2B.Ordering.Api/B2B.Ordering.Api.csproj" />
    <ProjectReference Include="../../samples/Migration.V1/Migration.V1.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Migration.V2/Migration.V2.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
