using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace B2B.Ordering.Api.Shared.OpenApi;

/// <summary>
/// OpenAPI document plus Swagger UI, exposed only in Development and Testing.
///
/// The document is generated by Microsoft.AspNetCore.OpenApi from the endpoints themselves;
/// Swashbuckle contributes the UI only, so there is no second source of truth for the schema.
/// </summary>
public static class OpenApiSetup
{
    public const string DocumentName = "v1";
    public const string BearerScheme = "Bearer";

    /// <summary>Route of the generated document, also used by the UI.</summary>
    public const string DocumentRoute = $"/openapi/{DocumentName}.json";

    public static IServiceCollection AddApiOpenApi(this IServiceCollection services) =>
        services.AddOpenApi(DocumentName, options =>
        {
            options.AddDocumentTransformer<ApiInfoTransformer>();
            options.AddDocumentTransformer<BearerSecurityTransformer>();
            options.AddOperationTransformer<TenantHeaderTransformer>();
            options.AddOperationTransformer<AnonymousOperationTransformer>();
        });

    /// <summary>
    /// Publishing the schema of a private API is a deliberate decision, so it is limited to the
    /// environments where a developer is the only audience.
    /// </summary>
    public static bool IsEnabledFor(IHostEnvironment environment) =>
        environment.IsDevelopment() || environment.IsEnvironment("Testing");

    public static WebApplication UseApiOpenApi(this WebApplication app)
    {
        if (!IsEnabledFor(app.Environment))
        {
            return app;
        }

        app.MapOpenApi(DocumentRoute).AllowAnonymous();

        app.UseSwaggerUI(ui =>
        {
            ui.SwaggerEndpoint(DocumentRoute, "B2B Ordering API v1");
            ui.RoutePrefix = "swagger";
            ui.DocumentTitle = "B2B Ordering API";
            ui.EnableTryItOutByDefault();
        });

        return app;
    }
}

/// <summary>Fills in the document metadata a reader needs before trying anything.</summary>
internal sealed class ApiInfoTransformer : IOpenApiDocumentTransformer
{
    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken)
    {
        document.Info = new OpenApiInfo
        {
            Title = "B2B Ordering API",
            Version = "v1",
            Description = """
                Synthetic B2B ordering case study.

                Every request to `/api/orders` needs three things: a bearer token whose
                `app_user_id` claim is a known user, an `X-Company-Id` header selecting the company
                to act for, and — for creation — an `Idempotency-Key`. The company header only
                selects a target; membership and role are verified against the database on every
                request, and a role claim inside the token is ignored.

                Failures use `application/problem+json` with a stable `errorCode` and a `traceId`.
                """,
        };

        return Task.CompletedTask;
    }
}

/// <summary>
/// Declares the bearer scheme once and applies it to the document, so "Try it out" in the UI can
/// actually authenticate against the real JwtBearer pipeline.
/// </summary>
internal sealed class BearerSecurityTransformer : IOpenApiDocumentTransformer
{
    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken)
    {
        var scheme = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            In = ParameterLocation.Header,
            Description =
                "Paste the token produced by `dotnet user-jwts create ... "
                + "--claim app_user_id=<user guid>`. The signature is really validated.",
        };

        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes[OpenApiSetup.BearerScheme] = scheme;

        document.Security =
        [
            new OpenApiSecurityRequirement
            {
                [new OpenApiSecuritySchemeReference(OpenApiSetup.BearerScheme, document)] = [],
            },
        ];

        return Task.CompletedTask;
    }
}

/// <summary>
/// The tenant headers are read by an endpoint filter rather than bound as parameters, so they are
/// invisible to the generator. They are added here for the whole order group, which is exactly the
/// set of endpoints the filter runs on.
/// </summary>
internal sealed class TenantHeaderTransformer : IOpenApiOperationTransformer
{
    public Task TransformAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        var pattern = context.Description.RelativePath ?? string.Empty;

        if (!pattern.StartsWith("api/orders", StringComparison.OrdinalIgnoreCase))
        {
            return Task.CompletedTask;
        }

        operation.Parameters ??= [];

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = "X-Company-Id",
            In = ParameterLocation.Header,
            Required = true,
            Description = "The company to act for. A missing or malformed value is a 400; a company "
                + "the caller has no active membership in is a 403.",
            Schema = new OpenApiSchema { Type = JsonSchemaType.String, Format = "uuid" },
        });

        if (context.Description.HttpMethod == HttpMethods.Post)
        {
            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "Idempotency-Key",
                In = ParameterLocation.Header,
                Required = true,
                Description = "1 to 128 printable ASCII characters, compared case sensitively. "
                    + "Repeating a key with the same payload replays the stored response; "
                    + "repeating it with a different payload is a 409.",
                Schema = new OpenApiSchema { Type = JsonSchemaType.String, MaxLength = 128 },
            });
        }

        return Task.CompletedTask;
    }
}

/// <summary>
/// The bearer requirement is declared once for the whole document so the UI shows a single
/// Authorize button. That would also mark the anonymous endpoints as protected, so they clear it
/// again here, driven by the same <c>AllowAnonymous</c> metadata the pipeline uses.
/// </summary>
internal sealed class AnonymousOperationTransformer : IOpenApiOperationTransformer
{
    public Task TransformAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        var isAnonymous = context.Description.ActionDescriptor.EndpointMetadata
            .OfType<IAllowAnonymous>()
            .Any();

        if (isAnonymous)
        {
            operation.Security = [];
        }

        return Task.CompletedTask;
    }
}
